name: darwinlm
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pytorch-cuda=12.1
  - pytorch==2.4.0
  - torchaudio==2.4.0
  - torchvision==0.19.0
  - transformers
  - accelerate
  - wandb